# Generated by Django 4.0.1 on 2023-05-06 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university_admissions_office', '0004_alter_faculty_options_alter_profession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'К выполнению'), ('to_check', 'На проверку'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=50, verbose_name='Статус задания')),
                ('solution_text', models.TextField(blank=True, null=True, verbose_name='Решение')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_admissions_office.student', verbose_name='Студент')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educ_proc_manager.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Назначенное задание',
                'verbose_name_plural': 'Назначенные задания',
                'unique_together': {('student', 'task')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(through='educ_proc_manager.TaskAssignment', to='university_admissions_office.Student', verbose_name='Студенты'),
        ),
        migrations.CreateModel(
            name='StudentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/attachments/students/')),
                ('task_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attachments', to='educ_proc_manager.taskassignment')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Прикрепленные файлы',
            },
        ),
        migrations.CreateModel(
            name='StaffAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/attachments/staff/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attachments', to='educ_proc_manager.task')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Прикрепленные файлы',
            },
        ),
    ]
