# Generated by Django 4.2 on 2023-04-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("university_admissions_office", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="profession",
        ),
        migrations.AddField(
            model_name="student",
            name="profession",
            field=models.ForeignKey(
                default=19,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="university_admissions_office.profession",
            ),
        ),
    ]
