# Generated by Django 4.2 on 2023-05-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "university_admissions_office",
            "0002_remove_student_profession_student_profession",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужской"), ("F", "Женский")], max_length=1
            ),
        ),
    ]
